#!/bin/bash

echo "options : $@"

while [[ $# > 0 ]]
do
key="$1"
shift
case $key in
    --dbid)
    #echo "--dbid : $2"
    export DB_CONNECT_STRING="$@"
    shift # past argument
    ;;

    *)
            # unknown option
    ;;
esac
#shift # past argument or value
done

echo "DB_CONNECT_STRING : ${DB_CONNECT_STRING}"

make cleanup
